SELECT * FROM cms_options AS f WHERE site_id IS NULL OR site_id = 42 ORDER BY site_id ;
SELECT * FROM cms_users AS f WHERE  (f.id = 49) LIMIT 1;
SELECT * FROM cms_roles AS f WHERE  (f.id = 9) LIMIT 1;
SELECT COUNT(*) as cnt FROM cms_roles_ref_users AS ru WHERE  (ru.user_id = "49") AND (ru.site_id = 42) AND (ru.role_id = "9") ;
SELECT COUNT(*) as cnt FROM cms_roles_ref_users AS ru  INNER JOIN cms_roles AS r ON r.id = ru.role_id WHERE r.site_id IS NULL AND (ru.user_id = "49") AND (ru.role_id = "9") ;
SELECT * FROM cms_options AS f WHERE site_id IS NULL OR site_id = 42 ORDER BY site_id ;
SELECT * FROM cms_users_settings AS s WHERE s.user_id = "49" AND (s.setting = "photo") ;
SELECT t.id,t.site_id,t.parent_id,t.program_id,t.element_id,taskR.id AS taskRequestId,t.type,t.display_type,t.description,t.title,t.threshold,t.evaluates_user,t.evaluate_user,t.scale_id,t.evaluate_type,t.is_deleted,t.allow_comments,t.order,t.assign_mode,t.auto_rule_id,t.created_at,t.updated_at,t.updated_by,t.created_by,t.period_of_execution,t.is_relative_period,t.not_block_after_expiration,u.date_start,u.date_finish,u.user_id,u.mark,u.attempts_count,u.is_tutor,u.have_answer_to_free_question,taskRefUser.id AS individualPlanId,u.attempts_limit,u.created_at as date_assign,(CASE WHEN t.`type` = "poll360" THEN (SELECT ps.status FROM els_polls360_result_statuses AS ps WHERE ps.task_id = t.id AND (ps.user_id = u.user_id) ORDER BY ps.id DESC LIMIT 1)
            ELSE u.`status` END) AS `status`,COUNT(trn.id) AS transactions_count FROM els_tasks AS t  INNER JOIN els_tasks_ref_users AS u ON u.task_id = t.id  LEFT JOIN els_individual_plan_ref_users AS taskRefUser ON taskRefUser.user_id = u.user_id AND taskRefUser.task_id = t.id LEFT JOIN els_tasks_requests AS taskR ON taskR.task_id = t.id AND taskR.user_id = 49  LEFT JOIN els_transactions AS trn ON trn.task_id = t.id AND trn.user_id = 49 WHERE u.user_id = "49" AND (t.is_deleted != 1) AND ((t.parent_id = t.id OR t.parent_id is null)) AND (t.site_id = 42) AND ((DATE(u.date_start) <= "2019-06-11" OR u.date_start IS NULL)) AND ((DATE(u.date_finish) >= "2019-06-11" OR u.date_finish IS NULL)) GROUP BY t.id HAVING `status` = "started" OR `status` = "inprogress" OR `status` = "not started" OR `status` IS NULL OR `status` = "verification" ORDER BY u.created_at DESC LIMIT 0, 5;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 4970 AND (user_id = 49) LIMIT 1;
SELECT * FROM els_courses AS f WHERE  (f.id = 543) AND (f.site_id = 42) LIMIT 1;
SELECT * FROM els_courses_files AS ft WHERE  (ft.course_id = "543") ;
SELECT ce.* FROM els_courses_plan AS ce WHERE ce.course_id = "543" AND (ce.is_determ_final_mark = 1) LIMIT 1;
SELECT f.* FROM cms_users AS f  INNER JOIN cms_sites_ref_users AS s ON s.user_id = f.id WHERE s.site_id = 42 AND (f.id = 2478) LIMIT 1;
SELECT p.id FROM cms_permissions AS p  INNER JOIN cms_roles_permissions AS rp ON rp.permission_id = p.id WHERE rp.role_id = "9" ;
SELECT * FROM cms_users_settings AS s WHERE s.user_id = "2478" AND (s.setting = "photo") ;
SELECT * FROM cms_users AS ft  INNER JOIN els_course_ref_users AS ref ON ref.user_id = ft.id WHERE  (ref.course_id = 543) ;
SELECT t.* FROM els_tasks AS t WHERE t.parent_id = "4970" AND (t.site_id = 42) AND (t.id != t.parent_id) AND (t.is_deleted != 1) ORDER BY t.order ;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 4977 AND (user_id = 49) LIMIT 1;
SELECT * FROM cms_sites AS s WHERE s.domain = "study.ime.com.ua" AND (s.is_active = 1) ;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 4976 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 4973 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 4974 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 4975 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 4972 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 4971 AND (user_id = 49) LIMIT 1;
SELECT * FROM els_courses AS f WHERE  (f.id = 543) AND (f.site_id = 42) LIMIT 1;
SELECT p.* FROM els_courses_plan AS p WHERE p.course_id = "543" ORDER BY p.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 3576 AND (a.course_id = 543) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 3577 AND (a.course_id = 543) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 3580 AND (a.course_id = 543) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 3579 AND (a.course_id = 543) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 3578 AND (a.course_id = 543) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 3581 AND (a.course_id = 543) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 3582 AND (a.course_id = 543) ORDER BY a.order ;
SELECT count(p.id) as count FROM els_courses_plan AS p WHERE p.course_id = 543 ;
SELECT * FROM els_tasks AS f WHERE  (f.id = 4970) AND (f.site_id = 42) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3680 AND (user_id = 49) LIMIT 1;
SELECT * FROM els_courses AS f WHERE  (f.id = 429) AND (f.site_id = 42) LIMIT 1;
SELECT * FROM els_courses_files AS ft WHERE  (ft.course_id = "429") ;
SELECT ce.* FROM els_courses_plan AS ce WHERE ce.course_id = "429" AND (ce.is_determ_final_mark = 1) LIMIT 1;
SELECT f.* FROM cms_users AS f  INNER JOIN cms_sites_ref_users AS s ON s.user_id = f.id WHERE s.site_id = 42 AND (f.id = 40) LIMIT 1;
SELECT * FROM cms_users_settings AS s WHERE s.user_id = "40" AND (s.setting = "photo") ;
SELECT * FROM cms_users AS ft  INNER JOIN els_course_ref_users AS ref ON ref.user_id = ft.id WHERE  (ref.course_id = 429) ;
SELECT t.* FROM els_tasks AS t WHERE t.parent_id = "3680" AND (t.site_id = 42) AND (t.id != t.parent_id) AND (t.is_deleted != 1) ORDER BY t.order ;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3695 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3694 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3693 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3692 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3691 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3690 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3689 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3688 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3687 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3686 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3685 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3684 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3683 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3682 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3681 AND (user_id = 49) LIMIT 1;
SELECT * FROM els_courses AS f WHERE  (f.id = 429) AND (f.site_id = 42) LIMIT 1;
SELECT p.* FROM els_courses_plan AS p WHERE p.course_id = "429" ORDER BY p.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 2687 AND (a.course_id = 429) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 2688 AND (a.course_id = 429) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 2689 AND (a.course_id = 429) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 2690 AND (a.course_id = 429) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 2691 AND (a.course_id = 429) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 2692 AND (a.course_id = 429) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 2693 AND (a.course_id = 429) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 2694 AND (a.course_id = 429) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 2695 AND (a.course_id = 429) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 2696 AND (a.course_id = 429) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 2697 AND (a.course_id = 429) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 2698 AND (a.course_id = 429) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 2699 AND (a.course_id = 429) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 2700 AND (a.course_id = 429) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 2701 AND (a.course_id = 429) ORDER BY a.order ;
SELECT count(p.id) as count FROM els_courses_plan AS p WHERE p.course_id = 429 ;
SELECT * FROM els_tasks AS f WHERE  (f.id = 3680) AND (f.site_id = 42) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3586 AND (user_id = 49) LIMIT 1;
SELECT * FROM els_tasks AS f WHERE  (f.id = 3586) AND (f.site_id = 42) LIMIT 1;
SELECT * FROM els_training_programs AS f WHERE  (f.id = 20) AND (f.site_id = 42) LIMIT 1;
SELECT count(s.id) as count FROM els_training_programs_structure AS s WHERE s.training_id = 20 ;
SELECT s.* FROM els_training_programs_structure AS s WHERE s.training_id = 20 ORDER BY s.order ;
SELECT * FROM els_courses AS f WHERE  (f.id = 392) AND (f.site_id = 42) LIMIT 1;
SELECT * FROM els_courses_files AS ft WHERE  (ft.course_id = "392") ;
SELECT ce.* FROM els_courses_plan AS ce WHERE ce.course_id = "392" AND (ce.is_determ_final_mark = 1) LIMIT 1;
SELECT f.* FROM cms_users AS f  INNER JOIN cms_sites_ref_users AS s ON s.user_id = f.id WHERE s.site_id = 42 AND (f.id = 2478) LIMIT 1;
SELECT * FROM cms_users_settings AS s WHERE s.user_id = "2478" AND (s.setting = "photo") ;
SELECT * FROM cms_users AS ft  INNER JOIN els_course_ref_users AS ref ON ref.user_id = ft.id WHERE  (ref.course_id = 392) ;
SELECT s.* FROM els_training_programs_structure AS s WHERE s.training_id = 20 AND (s.type = "course") AND (s.element_id = "392") ;
SELECT * FROM els_courses AS f WHERE  (f.id = 394) AND (f.site_id = 42) LIMIT 1;
SELECT * FROM els_courses_files AS ft WHERE  (ft.course_id = "394") ;
SELECT ce.* FROM els_courses_plan AS ce WHERE ce.course_id = "394" AND (ce.is_determ_final_mark = 1) LIMIT 1;
SELECT f.* FROM cms_users AS f  INNER JOIN cms_sites_ref_users AS s ON s.user_id = f.id WHERE s.site_id = 42 AND (f.id = 2478) LIMIT 1;
SELECT * FROM cms_users_settings AS s WHERE s.user_id = "2478" AND (s.setting = "photo") ;
SELECT * FROM cms_users AS ft  INNER JOIN els_course_ref_users AS ref ON ref.user_id = ft.id WHERE  (ref.course_id = 394) ;
SELECT s.* FROM els_training_programs_structure AS s WHERE s.training_id = 20 AND (s.type = "course") AND (s.element_id = "394") ;
SELECT * FROM els_courses AS f WHERE  (f.id = 397) AND (f.site_id = 42) LIMIT 1;
SELECT * FROM els_courses_files AS ft WHERE  (ft.course_id = "397") ;
SELECT ce.* FROM els_courses_plan AS ce WHERE ce.course_id = "397" AND (ce.is_determ_final_mark = 1) LIMIT 1;
SELECT f.* FROM cms_users AS f  INNER JOIN cms_sites_ref_users AS s ON s.user_id = f.id WHERE s.site_id = 42 AND (f.id = 2478) LIMIT 1;
SELECT * FROM cms_users_settings AS s WHERE s.user_id = "2478" AND (s.setting = "photo") ;
SELECT * FROM cms_users AS ft  INNER JOIN els_course_ref_users AS ref ON ref.user_id = ft.id WHERE  (ref.course_id = 397) ;
SELECT s.* FROM els_training_programs_structure AS s WHERE s.training_id = 20 AND (s.type = "course") AND (s.element_id = "397") ;
SELECT * FROM els_courses AS f WHERE  (f.id = 400) AND (f.site_id = 42) LIMIT 1;
SELECT * FROM els_courses_files AS ft WHERE  (ft.course_id = "400") ;
SELECT ce.* FROM els_courses_plan AS ce WHERE ce.course_id = "400" AND (ce.is_determ_final_mark = 1) LIMIT 1;
SELECT f.* FROM cms_users AS f  INNER JOIN cms_sites_ref_users AS s ON s.user_id = f.id WHERE s.site_id = 42 AND (f.id = 2478) LIMIT 1;
SELECT * FROM cms_users_settings AS s WHERE s.user_id = "2478" AND (s.setting = "photo") ;
SELECT * FROM cms_users AS ft  INNER JOIN els_course_ref_users AS ref ON ref.user_id = ft.id WHERE  (ref.course_id = 400) ;
SELECT s.* FROM els_training_programs_structure AS s WHERE s.training_id = 20 AND (s.type = "course") AND (s.element_id = "400") ;
SELECT * FROM els_courses AS f WHERE  (f.id = 375) AND (f.site_id = 42) LIMIT 1;
SELECT * FROM els_courses_files AS ft WHERE  (ft.course_id = "375") ;
SELECT ce.* FROM els_courses_plan AS ce WHERE ce.course_id = "375" AND (ce.is_determ_final_mark = 1) LIMIT 1;
SELECT f.* FROM cms_users AS f  INNER JOIN cms_sites_ref_users AS s ON s.user_id = f.id WHERE s.site_id = 42 AND (f.id = 2478) LIMIT 1;
SELECT * FROM cms_users_settings AS s WHERE s.user_id = "2478" AND (s.setting = "photo") ;
SELECT * FROM cms_users AS ft  INNER JOIN els_course_ref_users AS ref ON ref.user_id = ft.id WHERE  (ref.course_id = 375) ;
SELECT s.* FROM els_training_programs_structure AS s WHERE s.training_id = 20 AND (s.type = "course") AND (s.element_id = "375") ;
SELECT * FROM els_training_programs_files AS ft WHERE  (ft.training_id = "20") ;
SELECT t.* FROM els_tasks AS t WHERE t.parent_id = "3586" AND (t.site_id = 42) AND (t.id != t.parent_id) AND (t.is_deleted != 1) ORDER BY t.order ;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3587 AND (user_id = 49) LIMIT 1;
SELECT * FROM els_tasks AS f WHERE  (f.id = 3586) AND (f.site_id = 42) LIMIT 1;
SELECT tu.*,t.type,t.program_id FROM els_tasks_ref_users AS tu  INNER JOIN els_tasks AS t ON t.id = tu.task_id WHERE t.is_deleted != 1 AND (tu.task_id = "3587") AND (tu.user_id = "49") ;
SELECT * FROM els_courses AS f WHERE  (f.id = 392) AND (f.site_id = 42) LIMIT 1;
SELECT * FROM els_courses_files AS ft WHERE  (ft.course_id = "392") ;
SELECT ce.* FROM els_courses_plan AS ce WHERE ce.course_id = "392" AND (ce.is_determ_final_mark = 1) LIMIT 1;
SELECT f.* FROM cms_users AS f  INNER JOIN cms_sites_ref_users AS s ON s.user_id = f.id WHERE s.site_id = 42 AND (f.id = 2478) LIMIT 1;
SELECT * FROM cms_users_settings AS s WHERE s.user_id = "2478" AND (s.setting = "photo") ;
SELECT * FROM cms_users AS ft  INNER JOIN els_course_ref_users AS ref ON ref.user_id = ft.id WHERE  (ref.course_id = 392) ;
SELECT count(p.id) as count FROM els_courses_plan AS p WHERE p.course_id = 392 ;
SELECT * FROM els_courses AS f WHERE  (f.id = 392) AND (f.site_id = 42) LIMIT 1;
SELECT * FROM els_tasks AS f WHERE  (f.id = 3586) AND (f.site_id = 42) LIMIT 1;
SELECT t.* FROM els_tasks AS t WHERE t.parent_id = 3587 AND (t.site_id = 42) AND (t.id != t.parent_id) AND (t.is_deleted != 1) ORDER BY t.order ;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3590 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3589 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3588 AND (user_id = 49) LIMIT 1;
SELECT * FROM els_tasks AS f WHERE  (f.id = 3586) AND (f.site_id = 42) LIMIT 1;
SELECT tu.*,t.type,t.program_id FROM els_tasks_ref_users AS tu  INNER JOIN els_tasks AS t ON t.id = tu.task_id WHERE t.is_deleted != 1 AND (tu.task_id = "3587") AND (tu.user_id = "49") ;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3591 AND (user_id = 49) LIMIT 1;
SELECT * FROM els_tasks AS f WHERE  (f.id = 3586) AND (f.site_id = 42) LIMIT 1;
SELECT tu.*,t.type,t.program_id FROM els_tasks_ref_users AS tu  INNER JOIN els_tasks AS t ON t.id = tu.task_id WHERE t.is_deleted != 1 AND (tu.task_id = "3591") AND (tu.user_id = "49") ;
SELECT * FROM els_courses AS f WHERE  (f.id = 394) AND (f.site_id = 42) LIMIT 1;
SELECT * FROM els_courses_files AS ft WHERE  (ft.course_id = "394") ;
SELECT ce.* FROM els_courses_plan AS ce WHERE ce.course_id = "394" AND (ce.is_determ_final_mark = 1) LIMIT 1;
SELECT f.* FROM cms_users AS f  INNER JOIN cms_sites_ref_users AS s ON s.user_id = f.id WHERE s.site_id = 42 AND (f.id = 2478) LIMIT 1;
SELECT * FROM cms_users_settings AS s WHERE s.user_id = "2478" AND (s.setting = "photo") ;
SELECT * FROM cms_users AS ft  INNER JOIN els_course_ref_users AS ref ON ref.user_id = ft.id WHERE  (ref.course_id = 394) ;
SELECT count(p.id) as count FROM els_courses_plan AS p WHERE p.course_id = 394 ;
SELECT * FROM els_courses AS f WHERE  (f.id = 394) AND (f.site_id = 42) LIMIT 1;
SELECT * FROM els_tasks AS f WHERE  (f.id = 3586) AND (f.site_id = 42) LIMIT 1;
SELECT t.* FROM els_tasks AS t WHERE t.parent_id = 3591 AND (t.site_id = 42) AND (t.id != t.parent_id) AND (t.is_deleted != 1) ORDER BY t.order ;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3602 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3601 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3600 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3599 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3598 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3597 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3596 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3595 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3594 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3593 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3592 AND (user_id = 49) LIMIT 1;
SELECT * FROM els_tasks AS f WHERE  (f.id = 3586) AND (f.site_id = 42) LIMIT 1;
SELECT tu.*,t.type,t.program_id FROM els_tasks_ref_users AS tu  INNER JOIN els_tasks AS t ON t.id = tu.task_id WHERE t.is_deleted != 1 AND (tu.task_id = "3591") AND (tu.user_id = "49") ;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3618 AND (user_id = 49) LIMIT 1;
SELECT * FROM els_tasks AS f WHERE  (f.id = 3586) AND (f.site_id = 42) LIMIT 1;
SELECT tu.*,t.type,t.program_id FROM els_tasks_ref_users AS tu  INNER JOIN els_tasks AS t ON t.id = tu.task_id WHERE t.is_deleted != 1 AND (tu.task_id = "3618") AND (tu.user_id = "49") ;
SELECT * FROM els_courses AS f WHERE  (f.id = 397) AND (f.site_id = 42) LIMIT 1;
SELECT * FROM els_courses_files AS ft WHERE  (ft.course_id = "397") ;
SELECT ce.* FROM els_courses_plan AS ce WHERE ce.course_id = "397" AND (ce.is_determ_final_mark = 1) LIMIT 1;
SELECT f.* FROM cms_users AS f  INNER JOIN cms_sites_ref_users AS s ON s.user_id = f.id WHERE s.site_id = 42 AND (f.id = 2478) LIMIT 1;
SELECT * FROM cms_users_settings AS s WHERE s.user_id = "2478" AND (s.setting = "photo") ;
SELECT * FROM cms_users AS ft  INNER JOIN els_course_ref_users AS ref ON ref.user_id = ft.id WHERE  (ref.course_id = 397) ;
SELECT count(p.id) as count FROM els_courses_plan AS p WHERE p.course_id = 397 ;
SELECT * FROM els_courses AS f WHERE  (f.id = 397) AND (f.site_id = 42) LIMIT 1;
SELECT * FROM els_tasks AS f WHERE  (f.id = 3586) AND (f.site_id = 42) LIMIT 1;
SELECT t.* FROM els_tasks AS t WHERE t.parent_id = 3618 AND (t.site_id = 42) AND (t.id != t.parent_id) AND (t.is_deleted != 1) ORDER BY t.order ;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3630 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3629 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3628 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3627 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3626 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3625 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3624 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3623 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3622 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3620 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3619 AND (user_id = 49) LIMIT 1;
SELECT * FROM els_tasks AS f WHERE  (f.id = 3586) AND (f.site_id = 42) LIMIT 1;
SELECT tu.*,t.type,t.program_id FROM els_tasks_ref_users AS tu  INNER JOIN els_tasks AS t ON t.id = tu.task_id WHERE t.is_deleted != 1 AND (tu.task_id = "3618") AND (tu.user_id = "49") ;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3603 AND (user_id = 49) LIMIT 1;
SELECT * FROM els_tasks AS f WHERE  (f.id = 3586) AND (f.site_id = 42) LIMIT 1;
SELECT tu.*,t.type,t.program_id FROM els_tasks_ref_users AS tu  INNER JOIN els_tasks AS t ON t.id = tu.task_id WHERE t.is_deleted != 1 AND (tu.task_id = "3603") AND (tu.user_id = "49") ;
SELECT * FROM els_courses AS f WHERE  (f.id = 400) AND (f.site_id = 42) LIMIT 1;
SELECT * FROM els_courses_files AS ft WHERE  (ft.course_id = "400") ;
SELECT ce.* FROM els_courses_plan AS ce WHERE ce.course_id = "400" AND (ce.is_determ_final_mark = 1) LIMIT 1;
SELECT f.* FROM cms_users AS f  INNER JOIN cms_sites_ref_users AS s ON s.user_id = f.id WHERE s.site_id = 42 AND (f.id = 2478) LIMIT 1;
SELECT * FROM cms_users_settings AS s WHERE s.user_id = "2478" AND (s.setting = "photo") ;
SELECT * FROM cms_users AS ft  INNER JOIN els_course_ref_users AS ref ON ref.user_id = ft.id WHERE  (ref.course_id = 400) ;
SELECT count(p.id) as count FROM els_courses_plan AS p WHERE p.course_id = 400 ;
SELECT * FROM els_courses AS f WHERE  (f.id = 400) AND (f.site_id = 42) LIMIT 1;
SELECT * FROM els_tasks AS f WHERE  (f.id = 3586) AND (f.site_id = 42) LIMIT 1;
SELECT t.* FROM els_tasks AS t WHERE t.parent_id = 3603 AND (t.site_id = 42) AND (t.id != t.parent_id) AND (t.is_deleted != 1) ORDER BY t.order ;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3617 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3616 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3615 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3614 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3613 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3612 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3611 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3610 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3609 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3608 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3606 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3605 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3604 AND (user_id = 49) LIMIT 1;
SELECT * FROM els_tasks AS f WHERE  (f.id = 3586) AND (f.site_id = 42) LIMIT 1;
SELECT tu.*,t.type,t.program_id FROM els_tasks_ref_users AS tu  INNER JOIN els_tasks AS t ON t.id = tu.task_id WHERE t.is_deleted != 1 AND (tu.task_id = "3603") AND (tu.user_id = "49") ;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3631 AND (user_id = 49) LIMIT 1;
SELECT * FROM els_tasks AS f WHERE  (f.id = 3586) AND (f.site_id = 42) LIMIT 1;
SELECT tu.*,t.type,t.program_id FROM els_tasks_ref_users AS tu  INNER JOIN els_tasks AS t ON t.id = tu.task_id WHERE t.is_deleted != 1 AND (tu.task_id = "3631") AND (tu.user_id = "49") ;
SELECT * FROM els_courses AS f WHERE  (f.id = 375) AND (f.site_id = 42) LIMIT 1;
SELECT * FROM els_courses_files AS ft WHERE  (ft.course_id = "375") ;
SELECT ce.* FROM els_courses_plan AS ce WHERE ce.course_id = "375" AND (ce.is_determ_final_mark = 1) LIMIT 1;
SELECT f.* FROM cms_users AS f  INNER JOIN cms_sites_ref_users AS s ON s.user_id = f.id WHERE s.site_id = 42 AND (f.id = 2478) LIMIT 1;
SELECT * FROM cms_users_settings AS s WHERE s.user_id = "2478" AND (s.setting = "photo") ;
SELECT * FROM cms_users AS ft  INNER JOIN els_course_ref_users AS ref ON ref.user_id = ft.id WHERE  (ref.course_id = 375) ;
SELECT count(p.id) as count FROM els_courses_plan AS p WHERE p.course_id = 375 ;
SELECT * FROM els_courses AS f WHERE  (f.id = 375) AND (f.site_id = 42) LIMIT 1;
SELECT * FROM els_tasks AS f WHERE  (f.id = 3586) AND (f.site_id = 42) LIMIT 1;
SELECT t.* FROM els_tasks AS t WHERE t.parent_id = 3631 AND (t.site_id = 42) AND (t.id != t.parent_id) AND (t.is_deleted != 1) ORDER BY t.order ;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3634 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3633 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 3632 AND (user_id = 49) LIMIT 1;
SELECT * FROM els_tasks AS f WHERE  (f.id = 3586) AND (f.site_id = 42) LIMIT 1;
SELECT tu.*,t.type,t.program_id FROM els_tasks_ref_users AS tu  INNER JOIN els_tasks AS t ON t.id = tu.task_id WHERE t.is_deleted != 1 AND (tu.task_id = "3631") AND (tu.user_id = "49") ;
SELECT * FROM els_tasks AS f WHERE  (f.id = 3586) AND (f.site_id = 42) LIMIT 1;
SELECT tu.*,t.type,t.program_id FROM els_tasks_ref_users AS tu  INNER JOIN els_tasks AS t ON t.id = tu.task_id WHERE t.is_deleted != 1 AND (tu.task_id = "3586") AND (tu.user_id = "49") ;
SELECT * FROM els_tasks AS f WHERE  (f.id = 3586) AND (f.site_id = 42) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 2975 AND (user_id = 49) LIMIT 1;
SELECT * FROM els_courses AS f WHERE  (f.id = 281) AND (f.site_id = 42) LIMIT 1;
SELECT * FROM els_courses_files AS ft WHERE  (ft.course_id = "281") ;
SELECT ce.* FROM els_courses_plan AS ce WHERE ce.course_id = "281" AND (ce.is_determ_final_mark = 1) LIMIT 1;
SELECT f.* FROM cms_users AS f  INNER JOIN cms_sites_ref_users AS s ON s.user_id = f.id WHERE s.site_id = 42 AND (f.id = 40) LIMIT 1;
SELECT * FROM cms_users_settings AS s WHERE s.user_id = "40" AND (s.setting = "photo") ;
SELECT * FROM cms_users AS ft  INNER JOIN els_course_ref_users AS ref ON ref.user_id = ft.id WHERE  (ref.course_id = 281) ;
SELECT t.* FROM els_tasks AS t WHERE t.parent_id = "2975" AND (t.site_id = 42) AND (t.id != t.parent_id) AND (t.is_deleted != 1) ORDER BY t.order ;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 2986 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 2985 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 2984 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 2983 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 2982 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 2981 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 2980 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 2979 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 2978 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 2977 AND (user_id = 49) LIMIT 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 2976 AND (user_id = 49) LIMIT 1;
SELECT * FROM els_courses AS f WHERE  (f.id = 281) AND (f.site_id = 42) LIMIT 1;
SELECT p.* FROM els_courses_plan AS p WHERE p.course_id = "281" ORDER BY p.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 1577 AND (a.course_id = 281) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 1578 AND (a.course_id = 281) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 1579 AND (a.course_id = 281) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 1580 AND (a.course_id = 281) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 1581 AND (a.course_id = 281) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 1582 AND (a.course_id = 281) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 1583 AND (a.course_id = 281) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 1584 AND (a.course_id = 281) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 1585 AND (a.course_id = 281) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 1586 AND (a.course_id = 281) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 1587 AND (a.course_id = 281) ORDER BY a.order ;
SELECT count(p.id) as count FROM els_courses_plan AS p WHERE p.course_id = 281 ;
SELECT * FROM els_tasks AS f WHERE  (f.id = 2975) AND (f.site_id = 42) LIMIT 1;
SELECT COUNT(*) as cnt FROM els_tasks AS t  INNER JOIN els_tasks_ref_users AS tu ON tu.task_id = t.id WHERE (t.parent_id = 2975 OR t.program_id = 2975) AND (t.site_id = 42) AND (tu.user_id = 49) AND (t.id != t.parent_id) AND (t.is_deleted != 1) AND (tu.mark > 0) AND tu.status IN ("fail","finished") ;
SELECT t.id,t.site_id,t.parent_id,t.program_id,t.element_id,taskR.id AS taskRequestId,t.type,t.display_type,t.description,t.title,t.threshold,t.evaluates_user,t.evaluate_user,t.scale_id,t.evaluate_type,t.is_deleted,t.allow_comments,t.order,t.assign_mode,t.auto_rule_id,t.created_at,t.updated_at,t.updated_by,t.created_by,t.period_of_execution,t.is_relative_period,t.not_block_after_expiration,u.date_start,u.date_finish,u.user_id,u.mark,u.attempts_count,u.is_tutor,u.have_answer_to_free_question,taskRefUser.id AS individualPlanId,u.attempts_limit,u.created_at as date_assign,(CASE WHEN t.`type` = "poll360" THEN (SELECT ps.status FROM els_polls360_result_statuses AS ps WHERE ps.task_id = t.id AND (ps.user_id = u.user_id) ORDER BY ps.id DESC LIMIT 1)
            ELSE u.`status` END) AS `status`,COUNT(trn.id) AS transactions_count FROM els_tasks AS t  INNER JOIN els_tasks_ref_users AS u ON u.task_id = t.id  LEFT JOIN els_individual_plan_ref_users AS taskRefUser ON taskRefUser.user_id = u.user_id AND taskRefUser.task_id = t.id LEFT JOIN els_tasks_requests AS taskR ON taskR.task_id = t.id AND taskR.user_id = 49  LEFT JOIN els_transactions AS trn ON trn.task_id = t.id AND trn.user_id = 49 WHERE u.user_id = "49" AND (t.is_deleted != 1) AND ((t.parent_id = t.id OR t.parent_id is null)) AND (t.site_id = 42) AND ((DATE(u.date_start) <= "2019-06-11" OR u.date_start IS NULL)) AND ((DATE(u.date_finish) >= "2019-06-11" OR u.date_finish IS NULL)) GROUP BY t.id HAVING `status` = "started" OR `status` = "inprogress" OR `status` = "not started" OR `status` IS NULL OR `status` = "verification" ORDER BY u.created_at DESC LIMIT 0, 1;
SELECT * FROM els_courses AS f WHERE  (f.id = 543) AND (f.site_id = 42) LIMIT 1;
SELECT * FROM els_courses_files AS ft WHERE  (ft.course_id = "543") ;
SELECT ce.* FROM els_courses_plan AS ce WHERE ce.course_id = "543" AND (ce.is_determ_final_mark = 1) LIMIT 1;
SELECT f.* FROM cms_users AS f  INNER JOIN cms_sites_ref_users AS s ON s.user_id = f.id WHERE s.site_id = 42 AND (f.id = 2478) LIMIT 1;
SELECT * FROM cms_users_settings AS s WHERE s.user_id = "2478" AND (s.setting = "photo") ;
SELECT * FROM cms_users AS ft  INNER JOIN els_course_ref_users AS ref ON ref.user_id = ft.id WHERE  (ref.course_id = 543) ;
SELECT t.* FROM els_tasks AS t WHERE t.parent_id = "4970" AND (t.site_id = 42) AND (t.id != t.parent_id) AND (t.is_deleted != 1) ORDER BY t.order ;
SELECT * FROM els_courses AS f WHERE  (f.id = 543) AND (f.site_id = 42) LIMIT 1;
SELECT p.* FROM els_courses_plan AS p WHERE p.course_id = "543" ORDER BY p.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 3576 AND (a.course_id = 543) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 3577 AND (a.course_id = 543) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 3580 AND (a.course_id = 543) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 3579 AND (a.course_id = 543) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 3578 AND (a.course_id = 543) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 3581 AND (a.course_id = 543) ORDER BY a.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 3582 AND (a.course_id = 543) ORDER BY a.order ;
SELECT count(p.id) as count FROM els_courses_plan AS p WHERE p.course_id = 543 ;
SELECT * FROM els_tasks AS f WHERE  (f.id = 4970) AND (f.site_id = 42) LIMIT 1;
SELECT t.id,t.site_id,t.parent_id,t.program_id,t.element_id,taskR.id AS taskRequestId,t.type,t.display_type,t.description,t.title,t.threshold,t.evaluates_user,t.evaluate_user,t.scale_id,t.evaluate_type,t.is_deleted,t.allow_comments,t.order,t.assign_mode,t.auto_rule_id,t.created_at,t.updated_at,t.updated_by,t.created_by,t.period_of_execution,t.is_relative_period,t.not_block_after_expiration,u.date_start,u.date_finish,u.user_id,u.mark,u.attempts_count,u.is_tutor,u.have_answer_to_free_question,taskRefUser.id AS individualPlanId,u.attempts_limit,u.created_at as date_assign,(CASE WHEN t.`type` = "poll360" THEN (SELECT ps.status FROM els_polls360_result_statuses AS ps WHERE ps.task_id = t.id AND (ps.user_id = u.user_id) ORDER BY ps.id DESC LIMIT 1)
            ELSE u.`status` END) AS `status`,COUNT(trn.id) AS transactions_count FROM els_tasks AS t  INNER JOIN els_tasks_ref_users AS u ON u.task_id = t.id  LEFT JOIN els_individual_plan_ref_users AS taskRefUser ON taskRefUser.user_id = u.user_id AND taskRefUser.task_id = t.id LEFT JOIN els_tasks_requests AS taskR ON taskR.task_id = t.id AND taskR.user_id = 49  LEFT JOIN els_transactions AS trn ON trn.task_id = t.id AND trn.user_id = 49 WHERE u.user_id = "49" AND (t.is_deleted != 1) AND ((t.parent_id = t.id OR t.parent_id is null)) AND (t.site_id = 42) GROUP BY t.id HAVING status = "fail" ORDER BY u.created_at DESC LIMIT 0, 1;
SELECT t.id,t.site_id,t.parent_id,t.program_id,t.element_id,taskR.id AS taskRequestId,t.type,t.display_type,t.description,t.title,t.threshold,t.evaluates_user,t.evaluate_user,t.scale_id,t.evaluate_type,t.is_deleted,t.allow_comments,t.order,t.assign_mode,t.auto_rule_id,t.created_at,t.updated_at,t.updated_by,t.created_by,t.period_of_execution,t.is_relative_period,t.not_block_after_expiration,u.date_start,u.date_finish,u.user_id,u.mark,u.attempts_count,u.is_tutor,u.have_answer_to_free_question,taskRefUser.id AS individualPlanId,u.attempts_limit,u.created_at as date_assign,(CASE WHEN t.`type` = "poll360" THEN (SELECT ps.status FROM els_polls360_result_statuses AS ps WHERE ps.task_id = t.id AND (ps.user_id = u.user_id) ORDER BY ps.id DESC LIMIT 1)
            ELSE u.`status` END) AS `status`,COUNT(trn.id) AS transactions_count FROM els_tasks AS t  INNER JOIN els_tasks_ref_users AS u ON u.task_id = t.id  LEFT JOIN els_individual_plan_ref_users AS taskRefUser ON taskRefUser.user_id = u.user_id AND taskRefUser.task_id = t.id LEFT JOIN els_tasks_requests AS taskR ON taskR.task_id = t.id AND taskR.user_id = 49  LEFT JOIN els_transactions AS trn ON trn.task_id = t.id AND trn.user_id = 49 WHERE u.user_id = "49" AND (t.is_deleted != 1) AND ((t.parent_id = t.id OR t.parent_id is null)) AND (t.site_id = 42) GROUP BY t.id HAVING `status` = "finished" ORDER BY u.created_at DESC LIMIT 0, 1;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 32101 AND (user_id = 49) LIMIT 1;
SELECT * FROM els_courses AS f WHERE  (f.id = 1602) AND (f.site_id = 42) LIMIT 1;
SELECT * FROM els_courses_files AS ft WHERE  (ft.course_id = "1602") ;
SELECT ce.* FROM els_courses_plan AS ce WHERE ce.course_id = "1602" AND (ce.is_determ_final_mark = 1) LIMIT 1;
SELECT f.* FROM cms_users AS f  INNER JOIN cms_sites_ref_users AS s ON s.user_id = f.id WHERE s.site_id = 42 AND (f.id = 2478) LIMIT 1;
SELECT * FROM cms_users_settings AS s WHERE s.user_id = "2478" AND (s.setting = "photo") ;
SELECT * FROM cms_users AS ft  INNER JOIN els_course_ref_users AS ref ON ref.user_id = ft.id WHERE  (ref.course_id = 1602) ;
SELECT t.* FROM els_tasks AS t WHERE t.parent_id = "32101" AND (t.site_id = 42) AND (t.id != t.parent_id) AND (t.is_deleted != 1) ORDER BY t.order ;
SELECT u.* FROM els_tasks_ref_users AS u WHERE task_id = 32102 AND (user_id = 49) LIMIT 1;
SELECT * FROM els_courses AS f WHERE  (f.id = 1602) AND (f.site_id = 42) LIMIT 1;
SELECT p.* FROM els_courses_plan AS p WHERE p.course_id = "1602" ORDER BY p.order ;
SELECT a.*,r.title as resource_title FROM els_courses_additionals AS a  INNER JOIN els_resource_pages AS r ON r.id = a.resource_id WHERE a.plan_item_id = 16081 AND (a.course_id = 1602) ORDER BY a.order ;
SELECT count(p.id) as count FROM els_courses_plan AS p WHERE p.course_id = 1602 ;
SELECT * FROM els_tasks AS f WHERE  (f.id = 32101) AND (f.site_id = 42) LIMIT 1;
SELECT t.id,t.site_id,t.parent_id,t.program_id,t.element_id,taskR.id AS taskRequestId,t.type,t.display_type,t.description,t.title,t.threshold,t.evaluates_user,t.evaluate_user,t.scale_id,t.evaluate_type,t.is_deleted,t.allow_comments,t.order,t.assign_mode,t.auto_rule_id,t.created_at,t.updated_at,t.updated_by,t.created_by,t.period_of_execution,t.is_relative_period,t.not_block_after_expiration,u.date_start,u.date_finish,u.user_id,u.mark,u.attempts_count,u.is_tutor,u.have_answer_to_free_question,taskRefUser.id AS individualPlanId,u.attempts_limit,u.created_at as date_assign,(CASE WHEN t.`type` = "poll360" THEN (SELECT ps.status FROM els_polls360_result_statuses AS ps WHERE ps.task_id = t.id AND (ps.user_id = u.user_id) ORDER BY ps.id DESC LIMIT 1)
            ELSE u.`status` END) AS `status`,COUNT(trn.id) AS transactions_count FROM els_tasks AS t  INNER JOIN els_tasks_ref_users AS u ON u.task_id = t.id  LEFT JOIN els_individual_plan_ref_users AS taskRefUser ON taskRefUser.user_id = u.user_id AND taskRefUser.task_id = t.id LEFT JOIN els_tasks_requests AS taskR ON taskR.task_id = t.id AND taskR.user_id = 49  LEFT JOIN els_transactions AS trn ON trn.task_id = t.id AND trn.user_id = 49 WHERE u.user_id = "49" AND (t.is_deleted != 1) AND ((t.parent_id = t.id OR t.parent_id is null)) AND (t.site_id = 42) AND (DATE(u.date_finish) < "2019-06-11") GROUP BY t.id HAVING (`status` != "fail" AND `status` != "finished") OR `status` IS NULL ORDER BY u.created_at DESC LIMIT 0, 1;
SELECT t.id,t.site_id,t.parent_id,t.program_id,t.element_id,taskR.id AS taskRequestId,t.type,t.display_type,t.description,t.title,t.threshold,t.evaluates_user,t.evaluate_user,t.scale_id,t.evaluate_type,t.is_deleted,t.allow_comments,t.order,t.assign_mode,t.auto_rule_id,t.created_at,t.updated_at,t.updated_by,t.created_by,t.period_of_execution,t.is_relative_period,t.not_block_after_expiration,u.date_start,u.date_finish,u.user_id,u.mark,u.attempts_count,u.is_tutor,u.have_answer_to_free_question,taskRefUser.id AS individualPlanId,u.attempts_limit,u.created_at as date_assign,(CASE WHEN t.`type` = "poll360" THEN (SELECT ps.status FROM els_polls360_result_statuses AS ps WHERE ps.task_id = t.id AND (ps.user_id = u.user_id) ORDER BY ps.id DESC LIMIT 1)
            ELSE u.`status` END) AS `status`,COUNT(trn.id) AS transactions_count FROM els_tasks AS t  INNER JOIN els_tasks_ref_users AS u ON u.task_id = t.id  LEFT JOIN els_individual_plan_ref_users AS taskRefUser ON taskRefUser.user_id = u.user_id AND taskRefUser.task_id = t.id LEFT JOIN els_tasks_requests AS taskR ON taskR.task_id = t.id AND taskR.user_id = 49  LEFT JOIN els_transactions AS trn ON trn.task_id = t.id AND trn.user_id = 49 WHERE u.user_id = "49" AND (t.is_deleted != 1) AND ((t.parent_id = t.id OR t.parent_id is null)) AND (t.site_id = 42) AND (DATE(u.date_start) > "2019-06-11") GROUP BY t.id ORDER BY u.created_at DESC LIMIT 0, 1;
